backend:
  name: git-gateway
  branch: main

media_folder: "src/uploads"
public_folder: "/uploads"

site_url: https://vpnhub.uk
display_url: https://vpnhub.uk
logo_url: /uploads/privacy.svg

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Category", name: "category", widget: "string", default: "Tutorial" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
